const SellerActionTypes = {
  SELLER_FILE_UPLOAD_STATUS: "SELLER_FILE_UPLOAD_STATUS",
  SELLER_FILE_UPLOAD_COMPLETE: "SELLER_FILE_UPLOAD_COMPLETE",
  FETCH_SELLER_COLLECTIONS_START: "FETCH_SELLER_COLLECTIONS_START",
  FETCH_SELLER_COLLECTIONS_SUCCESS: "FETCH_SELLER_COLLECTIONS_SUCCESS",
  FETCH_SELLER_COLLECTIONS_FAILURE: "FETCH_SELLER_COLLECTIONS_FAILURE",
};

export default SellerActionTypes;
