const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  COLLECTION_ITEMS_STORE_START: "COLLECTION_ITEMS_STORE_START",
  COLLECTION_ITEMS_STORE_SUCCESS: "COLLECTION_ITEMS_STORE_SUCCESS",
  COLLECTION_ITEMS_STORE_FAILURE: "COLLECTION_ITEMS_STORE_FAILURE",
};

export default ShopActionTypes;
