export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART: "CLEAR_CART",
  CART_ITEMS_STORE_START: "CART_ITEMS_STORE_START",
  CART_ITEMS_STORE_SUCCESS: "CART_ITEMS_STORE_SUCCESS",
  CART_ITEMS_STORE_FAILURE: "CART_ITEMS_STORE_FAILURE",
  FETCH_CART_COLLECTION_SUCCESS: "FETCH_CART_COLLECTION_SUCCESS",
  FETCH_CART_COLLECTION_FAILURE: "FETCH_CART_COLLECTION_FAILURE",
};
